// ITEMS
export const GET_ITEMS = "GET_ITEMS";
export const ADD_ITEM = "ADD_ITEM";
export const EDIT_ITEM = "EDIT_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const ITEMS_LOADING = "ITEMS_LOADING";
export const ITEMS_CLEAR = "ITEMS_CLEAR";
export const ITEM_CLEAR_ACTIONS = "ITEM_CLEAR_ACTIONS";
// PAYMENTS
export const GET_PAYMENTS = "GET_PAYMENTS";
export const ADD_PAYMENT = "ADD_PAYMENT";
export const EDIT_PAYMENT = "EDIT_PAYMENT";
export const DELETE_PAYMENT = "DELETE_PAYMENT";
export const PAYMENTS_LOADING = "PAYMENTS_LOADING";
export const CLEAR_PAYMENTS = "CLEAR_PAYMENTS";
export const PAYMENTS_CLEAR_ACTIONS = "PAYMENTS_CLEAR_ACTIONS";

// KEYS
export const GET_KEYS = "GET_KEYS";
export const ADD_KEY = "ADD_KEY";
export const GET_DB_KEYS = "GET_DB_KEYS";
export const ADD_DB_KEY = "ADD_DB_KEY";
export const SAVE_DB_KEYS = "SAVE_DB_KEYS";
export const DELETE_KEYS = "DELETE_KEYS";
export const KEYS_CLEAR_ACTIONS = "KEYS_CLEAR_ACTIONS";

// MODALS --DEFUNC
export const MODAL_TOGGLE = "MODAL_TOGGLE";
export const MODAL_ACTIVATE = "MODAL_ACTIVATE";
// USERS
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const GET_USERS = "GET_USERS";
export const ADD_USER = "ADD_USER";
export const EDIT_USER = "EDIT_USER";
export const DELETE_USER = "DELETE_USER";
export const USER_CLEAR_ACTIONS = "USER_CLEAR_ACTIONS";

// AUTHORIZATION
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const AUTH_CLEAR_ACTIONS = "AUTH_CLEAR_ACTIONS";

// FILTERS
export const GET_FILTERS = "GET_FIILTERS";
export const ADD_FILTER = "ADD_FILTER";
export const DELETE_FILTER = "DELETE_FILTER";
export const EDIT_FILTER = "EDIT_FILTER";
export const FILTERS_CLEAR = "FILTERS_CLEAR";
export const FILTERS_CLEAR_ACTIONS = "FILTERS_CLEAR_ACTIONS";

// ALERTS
export const GET_ALERTS = "GET_ALERTS";
export const CLEAR_ALERTS = "CLEAR_ALERTS";
export const ALERTS_CLEAR_ACTIONS = "ALERTS_CLEAR_ACTIONS";

// SKUS
export const GET_PRODUCTS = "GET_PRODUCTS";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const PRODUCTS_CLEAR_ACTIONS = "PRODUCTS_CLEAR_ACTIONS";

// Ordered Skus
export const GET_ORDEREDSKUS = "GET_ORDEREDSKUS";
export const ADD_ORDEREDSKU = "ADD_ORDEREDSKU";
export const EDIT_ORDEREDSKU = "EDIT_ORDEREDSKU";
export const DELETE_ORDEREDSKU = "DELETE_ORDEREDSKU";
export const CLEAR_ORDEREDSKUS = "CLEAR_ORDEREDSKUS";
export const ORDEREDSKUS_CLEAR_ACTIONS = "ORDEREDSKUS_CLEAR_ACTIONS";

// NOTES
export const GET_NOTES = "GET_NOTES";
export const ADD_NOTE = "ADD_NOTE";
export const EDIT_NOTE = "EDIT_NOTE";
export const DELETE_NOTE = "DELETE_NOTE";
export const CLEAR_NOTES = "CLEAR_NOTES";
export const NOTES_CLEAR_ACTIONS = "NOTES_CLEAR_ACTIONS";

// CLAIMS
export const GET_CLAIMS = "GET_CLAIMS";
export const ADD_CLAIM = "ADD_CLAIM";
export const EDIT_CLAIM = "EDIT_CLAIM";
export const DELETE_CLAIM = "DELETE_CLAIM";
export const CLEAR_CLAIMS = "CLEAR_CLAIMS";
export const CLAIMS_CLEAR_ACTIONS = "CLAIMS_CLEAR_ACTIONS";
